version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./postgres-db-volume:/var/lib/postgresql/data
            - ./sql_files:/store_files_psql
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "airflow"]
          interval: 5s
          retries: 5
        restart: always

    mysql:
        image: mysql:5.7.27
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            -  ./store_files:/store_files_mysql/
            - ./mysql.cnf:/etc/mysql/mysql.cnf

    webserver:
        image: puckel/docker-airflow:1.10.9
        #puckel/docker-airflow:1.10.9
        #image: apache/airflow:1.10.10
        restart: always
        depends_on:
            - postgres
            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=y
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
            - AIRFLOW__SMTP__SMTP_USER=kchuying@gmail.com
            - AIRFLOW__SMTP__SMTP_PASSWORD=djrqbqkcgxpfltmk
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=Airflow

        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./store_files:/usr/local/airflow/store_files_airflow
            - ./store_files/data_error_logs:/usr/local/airflow/store_files_airflow/data_error_logs
            - ./store_files/data_files:/usr/local/airflow/store_files_airflow/data_files
            - ./store_files/sql_data_files:/usr/local/airflow/store_files_airflow/sql_data_files
            - ./sql_files:/usr/local/airflow/sql_files
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    redis:
        image: redis:3.2.7
